import torch
from data import getSpeakerDataset
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as pyplot
import matplotlib.cm as cm

def visualize_embedding(model, folder):
	"""
	Used to visualize the speaker embeddings generated by the embedding model.
	"""

	dataset = getSpeakerDataset(folder)["data"]
	colors = cm.rainbow(np.linspace(0, 1, dataset.num_speakers))

	num_speakers = dataset.num_speakers
	embeddings = []
	speakers = []
	dataloader = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=False)

	for waveform, speaker in dataloader:
		embeddings.append(model(waveform).view(model.embedding_size).detach().numpy())
		speakers.append(int(speaker))
	embeddings = np.array(embeddings)

	pca = PCA(n_components=2)
	pca.fit(embeddings)

	data_new = pca.transform(embeddings)
	
	for idx in range(len(data_new)):
		data = data_new[idx]
		pyplot.scatter(data[0], data[1], c=colors[speakers[idx]%len(colors)])

	pyplot.show()

	return

if __name__ == '__main__':
	model = torch.load("saved_models/embd_clsr_100.pt")
	visualize_embedding(model, "../audio/libri-speech-small")